version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: local-elasticsearch
    environment:
      - node.name=es-node-01
      - cluster.name=es-learning-cluster
      - discovery.type=single-node
      - xpack.security.enabled=false  # 학습용으로 보안 비활성화
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"  # 메모리 제한 (로컬 환경)
    ports:
      - "30200:9200"  # Elasticsearch REST API
      - "30300:9300"  # Elasticsearch 노드 간 통신
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: local-kibana
    ports:
      - "30601:5601"  # Kibana 웹 UI
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - elastic

volumes:
  esdata:
    driver: local

networks:
  elastic:
    driver: bridge
